import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { DEFAULT_THEME, THEME_KEY } from "@/lib/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ammar Mujahid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = cookies().get(THEME_KEY);
  return (
    <html lang="en" className={theme?.value ?? DEFAULT_THEME}>
      <body className={`inter.className bg-[#F0F0F4] dark:bg-primary-darkest `}>
        {children}
      </body>
    </html>
  );
}
